### ISSUE TITLE
Featurerequest: Run boilerpipe as a command line tool

### ISSUE THREAD

**Issue by GoogleCodeExporter** [k-bx/boilerpipe#20]
```
Is it possible to use Boilerpipe as a CLI app together with other bash 
commands, e.g. extract the text of an entire website with a command like: 

wget -p http://mysite.com | boilerplate -options > file#.html 
```

Original issue reported on code.google.com by `haraldgr...@gmail.com` on 22 Mar 2011 at 3:26

**Comment by Nebuchadrezzar** [comment]
A couple of years later, and I'm still wishing for this feature...

**Comment by k-bx** [comment]
@Nebuchadrezzar today is your lucky day, haha. Spent some time and added this, please check out README on how to build and run from command-line.
